saveExact: true
blockExoticSubdeps: true
lockfileIncludeTarballUrl: true
verifyDepsBeforeRun: prompt
verifyStoreIntegrity: true

minimumReleaseAge: 4320
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'

allowUnusedPatches: false

strictDepBuilds: true
allowBuilds:
  'core-js': false

dedupePeers: true
dedupePeerDependents: true
strictPeerDependencies: true

overrides:
  'danger@13.0.10>undici@<6.28.1': '^6.28.1'
