// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only
import type { Tagged } from 'type-fest';
import * as z from 'zod/mini';
import { Base64 } from '../encodings/Base64.std.ts';
import type { Bytes } from '../encodings/Bytes.std.ts';

/**
 * 16 randomly generated bytes for generating a group invite link along with
 * the master key.
 * @public
 */
export type GroupInviteLinkPassword = GroupInviteLinkPassword.Decoded;

export namespace GroupInviteLinkPassword {
  export const SIZE = 16;

  type Opaque = Tagged<unknown, 'GroupInviteLinkPassword'>;

  /** @public */
  export type Decoded = Base64.Of<Opaque>;
  /** @public */
  export type Encoded = Bytes.Of<Opaque>;

  /** @public */
  export const Schema: z.ZodMiniType<GroupInviteLinkPassword, string> = z.pipe(
    Base64.Schema,
    z.custom<GroupInviteLinkPassword>(input => {
      return Base64.toBytes(input).byteLength === SIZE;
    })
  );

  /** @public */
  export function isValid(input: string): input is GroupInviteLinkPassword {
    return Schema.safeParse(input).success;
  }

  /** @public */
  export function fromBase64(input: Base64): GroupInviteLinkPassword {
    return Schema.parse(input);
  }

  /** @public */
  export function decode(input: Encoded): GroupInviteLinkPassword {
    return Base64.fromBytes(input);
  }

  /** @public */
  export function encode(input: GroupInviteLinkPassword): Encoded {
    return Base64.toBytes(input);
  }
}
