// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only
import type { Tagged } from 'type-fest';
import * as z from 'zod/mini';
import { Uint16 } from '../numbers/Uint16.std.ts';

/**
 * An id randomly generated by the client at install time.
 * @public
 */
export type RegistrationId = Tagged<Uint16, 'RegistrationId'>;

export namespace RegistrationId {
  /** @public */
  export const Schema: z.ZodMiniType<RegistrationId, number> = z.pipe(
    Uint16.Schema,
    z.custom<RegistrationId>()
  );

  /** @public */
  export function isValid(input: number): input is RegistrationId {
    return Schema.safeParse(input).success;
  }

  /** @public */
  export function fromUint16(input: Uint16): RegistrationId {
    return Schema.parse(input);
  }

  /** @public */
  export function fromNumber(input: number): RegistrationId {
    return fromUint16(Uint16.fromNumber(input));
  }
}
