// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only
import type { Tagged } from 'type-fest';
import * as z from 'zod/mini';
import { Base64 } from '../encodings/Base64.std.ts';
import type { Bytes } from '../encodings/Bytes.std.ts';

/**
 * A token generated by the server on unsealed envelopes for reporting a
 * message as spam to the server.
 * @public
 */
export type ReportSpamToken = ReportSpamToken.Decoded;

export namespace ReportSpamToken {
  type Opaque = Tagged<unknown, 'ReportSpamToken'>;

  /** @public */
  export type Decoded = Base64.Of<Opaque>;
  /** @public */
  export type Encoded = Bytes.Of<Opaque>;

  /** @public */
  export const Schema: z.ZodMiniType<ReportSpamToken, string> = z.pipe(
    Base64.Schema,
    z.custom<ReportSpamToken>()
  );

  /** @public */
  export function isValid(input: string): input is ReportSpamToken {
    return Schema.safeParse(input).success;
  }

  /** @public */
  export function fromBase64(input: Base64): ReportSpamToken {
    return Schema.parse(input);
  }

  /** @public */
  export function decode(input: Encoded): ReportSpamToken {
    return Base64.fromBytes(input);
  }

  /** @public */
  export function encode(input: ReportSpamToken): Encoded {
    return Base64.toBytes(input);
  }
}
