// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

export type _AxoSymbolName =
  | 'album'
  | 'album-fill'
  | 'album-plus'
  | 'album-plus-fill'
  | 'appearance'
  | 'appearance-fill'
  | 'archive'
  | 'archive-fill'
  | 'archive-down'
  | 'archive-down-fill'
  | 'archive-up'
  | 'archive-up-fill'
  | 'archive-alt-down'
  | 'archive-alt-down-fill'
  | 'archive-alt-up'
  | 'archive-alt-up-fill'
  | 'arrow-[start]'
  | 'arrow-[end]'
  | 'arrow-up'
  | 'arrow-down'
  | 'arrow-up[start]'
  | 'arrow-up[end]'
  | 'arrow-down[start]'
  | 'arrow-down[end]'
  | 'arrow-circle-[start]'
  | 'arrow-circle-[start]-fill'
  | 'arrow-circle-[end]'
  | 'arrow-circle-[end]-fill'
  | 'arrow-circle-up'
  | 'arrow-circle-up-fill'
  | 'arrow-circle-down'
  | 'arrow-circle-down-fill'
  | 'arrow-circle-up[start]'
  | 'arrow-circle-up[start]-fill'
  | 'arrow-circle-up[end]'
  | 'arrow-circle-up[end]-fill'
  | 'arrow-circle-down[start]'
  | 'arrow-circle-down[start]-fill'
  | 'arrow-circle-down[end]'
  | 'arrow-circle-down[end]-fill'
  | 'arrow-square-[start]'
  | 'arrow-square-[start]-fill'
  | 'arrow-square-[end]'
  | 'arrow-square-[end]-fill'
  | 'arrow-square-up'
  | 'arrow-square-up-fill'
  | 'arrow-square-down'
  | 'arrow-square-down-fill'
  | 'arrow-square-up[start]'
  | 'arrow-square-up[start]-fill'
  | 'arrow-square-up[end]'
  | 'arrow-square-up[end]-fill'
  | 'arrow-square-down[start]'
  | 'arrow-square-down[start]-fill'
  | 'arrow-square-down[end]'
  | 'arrow-square-down[end]-fill'
  | 'arrow-rectangle-[start]'
  | 'arrow-rectangle-[start]-fill'
  | 'arrow-rectangle-[end]'
  | 'arrow-rectangle-[end]-fill'
  | 'arrow-rectangle-up'
  | 'arrow-rectangle-up-fill'
  | 'arrow-rectangle-down'
  | 'arrow-rectangle-down-fill'
  | 'arrow-circle-dashed-[start]'
  | 'arrow-circle-dashed-[end]'
  | 'arrow-circle-dashed-up'
  | 'arrow-circle-dashed-down'
  | 'arrow-circle-dashed-up[start]'
  | 'arrow-circle-dashed-up[end]'
  | 'arrow-circle-dashed-down[start]'
  | 'arrow-circle-dashed-down[end]'
  | 'arrow-left-right'
  | 'arrow-up-down'
  | 'arrow-square-left-right'
  | 'arrow-square-left-right-fill'
  | 'arrow-square-up-down'
  | 'arrow-square-up-down-fill'
  | 'arrow-outward-upleft-upright-downleft-downright'
  | 'arrow-outward-up[end]-down[start]'
  | 'arrow-outward-up[start]-down[end]'
  | 'arrow-inward-upleft-upright-downleft-downright'
  | 'arrow-inward-up[end]-down[start]'
  | 'arrow-inward-up[start]-down[end]'
  | 'arrow-square-outward-up[end]-down[start]'
  | 'arrow-square-outward-up[end]-down[start]-fill'
  | 'arrow-square-outward-up[start]-down[end]'
  | 'arrow-square-outward-up[start]-down[end]-fill'
  | 'arrow-square-inward-up[end]-down[start]'
  | 'arrow-square-inward-up[end]-down[start]-fill'
  | 'arrow-square-inward-up[start]-down[end]'
  | 'arrow-square-inward-up[start]-down[end]-fill'
  | 'arrow-clockwise'
  | 'arrow-counterclockwise'
  | 'aspectratio'
  | 'aspectratio-fill'
  | 'at'
  | 'attach'
  | 'audio'
  | 'audio-rectangle'
  | 'audio-rectangle-fill'
  | 'audio-rectangle-slash'
  | 'audio-rectangle-slash-fill'
  | 'backspace'
  | 'backspace-fill'
  | 'backup'
  | 'backup-signal'
  | 'backup-error'
  | 'badge'
  | 'badge-fill'
  | 'badge-set'
  | 'badge-set-fill'
  | 'bear'
  | 'bell'
  | 'bell-fill'
  | 'bell-ring'
  | 'bell-ring-fill'
  | 'bell-badge'
  | 'bell-badge-fill'
  | 'bell-slash'
  | 'bell-slash-fill'
  | 'bell-sleep'
  | 'bell-sleep-fill'
  | 'block'
  | 'blur'
  | 'blur-light'
  | 'blur-medium'
  | 'blur-heavy'
  | 'bolt'
  | 'bolt-fill'
  | 'boost'
  | 'boost-fill'
  | 'brushsize-thin'
  | 'brushsize-regular'
  | 'brushsize-medium'
  | 'brushsize-heavy'
  | 'building'
  | 'building-fill'
  | 'calendar'
  | 'calendar-fill'
  | 'calendar-week'
  | 'calendar-week-fill'
  | 'calendar-day'
  | 'calendar-day-fill'
  | 'calendar-blank'
  | 'calendar-blank-fill'
  | 'calendar-search'
  | 'camera'
  | 'camera-fill'
  | 'camera-swap'
  | 'camera-swap-fill'
  | 'car'
  | 'cellularbars'
  | 'check'
  | 'check-circle'
  | 'check-circle-fill'
  | 'check-square'
  | 'check-square-fill'
  | 'check-circle-on-check-circle'
  | 'check-circle-on-check-circle-fill'
  | 'chevron-[start]'
  | 'chevron-[end]'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevron-circle-[start]'
  | 'chevron-circle-[start]-fill'
  | 'chevron-circle-[end]'
  | 'chevron-circle-[end]-fill'
  | 'chevron-circle-up'
  | 'chevron-circle-up-fill'
  | 'chevron-circle-down'
  | 'chevron-circle-down-fill'
  | 'chevron-square-[start]'
  | 'chevron-square-[start]-fill'
  | 'chevron-square-[end]'
  | 'chevron-square-[end]-fill'
  | 'chevron-square-up'
  | 'chevron-square-up-fill'
  | 'chevron-square-down'
  | 'chevron-square-down-fill'
  | 'chevron-shallow-[start]'
  | 'chevron-shallow-[end]'
  | 'chevron-shallow-up'
  | 'chevron-shallow-down'
  | 'chevron-outward-left-right'
  | 'chevron-outward-up-down'
  | 'chevron-rectangle-outward-upright-downleft'
  | 'chevron-rectangle-outward-up[end]-down[start]-fill'
  | 'circle'
  | 'circle-fill'
  | 'circle-dashed'
  | 'clock'
  | 'clock-hour-1'
  | 'clock-hour-2'
  | 'clock-hour-3'
  | 'clock-hour-4'
  | 'clock-hour-5'
  | 'clock-hour-6'
  | 'clock-hour-7'
  | 'clock-hour-8'
  | 'clock-hour-9'
  | 'clock-hour-10'
  | 'clock-hour-11'
  | 'clock-hour-12'
  | 'compose'
  | 'connections'
  | 'connections-fill'
  | 'contrast'
  | 'copy'
  | 'copy-alt'
  | 'creditcard'
  | 'creditcard-fill'
  | 'crop'
  | 'crop-rotate'
  | 'crop-lock'
  | 'crop-unlock'
  | 'cube'
  | 'cube-fill'
  | 'cube-badge'
  | 'cube-badge-fill'
  | 'device-phone'
  | 'device-phone-fill'
  | 'device-tablet'
  | 'device-tablet-fill'
  | 'device-laptop'
  | 'device-laptop-fill'
  | 'device-phone-laptop'
  | 'device-phone-laptop-fill'
  | 'download'
  | 'draghandle'
  | 'draghandle-alt'
  | 'drive'
  | 'drive-fill'
  | 'drive-down'
  | 'drive-down-fill'
  | 'dropper'
  | 'dropper-fill'
  | 'emoticon'
  | 'error'
  | 'error-circle'
  | 'error-circle-fill'
  | 'error-triangle'
  | 'error-triangle-fill'
  | 'error-octagon'
  | 'error-octagon-fill'
  | 'eyes'
  | 'face-smiling'
  | 'face-smiling-fill'
  | 'face-smiling-plus'
  | 'face-excited'
  | 'face-sad'
  | 'face-angry'
  | 'file'
  | 'file-fill'
  | 'file-slash'
  | 'file-slash-fill'
  | 'filter'
  | 'filter-circle'
  | 'filter-circle-fill'
  | 'flag'
  | 'flag-fill'
  | 'flash'
  | 'flash-fill'
  | 'flash-slash'
  | 'flash-slash-fill'
  | 'flash-auto'
  | 'flash-auto-fill'
  | 'flip'
  | 'folder'
  | 'folder-plus'
  | 'folder-minus'
  | 'folder-settings'
  | 'forward'
  | 'forward-fill'
  | 'fullscreen'
  | 'gif'
  | 'gif-rectangle'
  | 'gif-rectangle-fill'
  | 'gift'
  | 'gift-fill'
  | 'globe'
  | 'globe-fill'
  | 'grid'
  | 'grid-fill'
  | 'grid-rectangle'
  | 'grid-rectangle-fill'
  | 'grid-sidebar'
  | 'grid-sidebar-fill'
  | 'group'
  | 'group-fill'
  | 'group-x'
  | 'group-x-fill'
  | 'group-question'
  | 'group-question-fill'
  | 'hd'
  | 'hd-fill'
  | 'hd-slash'
  | 'hd-slash-fill'
  | 'headphones'
  | 'headphones-fill'
  | 'heart'
  | 'heart-fill'
  | 'heart-plus'
  | 'heart-plus-fill'
  | 'hexagon'
  | 'hexagon-fill'
  | 'info'
  | 'info-circle'
  | 'info-circle-fill'
  | 'invite'
  | 'invite-fill'
  | 'key'
  | 'key-fill'
  | 'key-slash'
  | 'key-slash-fill'
  | 'key-horizontal'
  | 'key-horizontal-fill'
  | 'key-vertical'
  | 'key-vertical-fill'
  | 'keyboard'
  | 'keyboard-fill'
  | 'label'
  | 'label-fill'
  | 'leave'
  | 'lightbulb'
  | 'link'
  | 'link-alt'
  | 'link-broken'
  | 'link-slash'
  | 'list-bullet'
  | 'list-circle'
  | 'location'
  | 'location-fill'
  | 'location-circle'
  | 'location-circle-fill'
  | 'lock'
  | 'lock-fill'
  | 'lock-open'
  | 'lock-open-fill'
  | 'mathsymbols-square'
  | 'mathsymbols-square-fill'
  | 'megaphone'
  | 'megaphone-fill'
  | 'menu'
  | 'merge'
  | 'message'
  | 'message-fill'
  | 'message-badge'
  | 'message-badge-fill'
  | 'message-arrow-forward'
  | 'message-arrow-forward-fill'
  | 'message-check'
  | 'message-check-fill'
  | 'message-more'
  | 'message-more-fill'
  | 'message-x'
  | 'message-x-fill'
  | 'message-thread'
  | 'message-thread-fill'
  | 'mic'
  | 'mic-fill'
  | 'mic-slash'
  | 'mic-slash-fill'
  | 'minus'
  | 'minus-circle'
  | 'minus-circle-fill'
  | 'minus-square'
  | 'minus-square-fill'
  | 'missed-incoming'
  | 'missed-outgoing'
  | 'moon'
  | 'moon-fill'
  | 'moon-slash'
  | 'moon-slash-fill'
  | 'more'
  | 'more-vertical'
  | 'more-circle'
  | 'more-circle-fill'
  | 'more-square'
  | 'more-square-fill'
  | 'note'
  | 'note-fill'
  | 'nothing'
  | 'number'
  | 'number-square'
  | 'number-square-fill'
  | 'numberpad'
  | 'octagon'
  | 'octagon-fill'
  | 'open'
  | 'palette'
  | 'palette-fill'
  | 'pause'
  | 'pause-fill'
  | 'pause-circle'
  | 'pause-circle-fill'
  | 'pause-square'
  | 'pause-square-fill'
  | 'pencil'
  | 'pencil-fill'
  | 'person'
  | 'person-fill'
  | 'person-check'
  | 'person-check-fill'
  | 'person-key'
  | 'person-key-fill'
  | 'person-plus'
  | 'person-plus-fill'
  | 'person-minus'
  | 'person-minus-fill'
  | 'person-x'
  | 'person-x-fill'
  | 'person-question'
  | 'person-question-fill'
  | 'person-circle'
  | 'person-circle-fill'
  | 'person-circle-plus'
  | 'person-square'
  | 'person-square-fill'
  | 'person-rectangle'
  | 'person-rectangle-fill'
  | 'person-background'
  | 'person-background-fill'
  | 'phone'
  | 'phone-fill'
  | 'phone-horiztonal'
  | 'phone-horiztonal-fill'
  | 'phone-plus'
  | 'phone-plus-fill'
  | 'phone-speaker'
  | 'phone-speaker-fill'
  | 'phone-slash'
  | 'phone-slash-fill'
  | 'photo'
  | 'photo-fill'
  | 'photo-slash'
  | 'photo-slash-fill'
  | 'piechart'
  | 'piechart-fill'
  | 'pin'
  | 'pin-fill'
  | 'pin-slash'
  | 'pin-slash-fill'
  | 'pip'
  | 'pip-fill'
  | 'play'
  | 'play-fill'
  | 'play-slash'
  | 'play-slash-fill'
  | 'play-circle'
  | 'play-circle-fill'
  | 'play-square'
  | 'play-square-fill'
  | 'play-rectangle'
  | 'play-rectangle-fill'
  | 'play-rectangle-slash'
  | 'play-rectangle-slash-fill'
  | 'plus'
  | 'plus-circle'
  | 'plus-circle-fill'
  | 'plus-square'
  | 'plus-square-fill'
  | 'poll'
  | 'poll-fill'
  | 'press'
  | 'press-fill'
  | 'qrcode'
  | 'question'
  | 'question-circle'
  | 'question-circle-fill'
  | 'raisehand'
  | 'raisehand-fill'
  | 'receipt'
  | 'receipt-fill'
  | 'recent'
  | 'recent-fill'
  | 'rectangle'
  | 'rectangle-fill'
  | 'rectangle-dashed'
  | 'rectangle-portrait'
  | 'rectangle-portrait-fill'
  | 'rectangle-portrait-dashed'
  | 'redo'
  | 'reply'
  | 'reply-fill'
  | 'rotate'
  | 'rotate-fill'
  | 'scan'
  | 'scan-qrcode'
  | 'scribble'
  | 'seal-fill'
  | 'seal'
  | 'seal-check'
  | 'seal-check-fill'
  | 'search'
  | 'securitykey'
  | 'securitykey-fill'
  | 'send'
  | 'send-fill'
  | 'settings'
  | 'settings-fill'
  | 'settings-alt'
  | 'share'
  | 'share-alt'
  | 'shield'
  | 'shield-fill'
  | 'shield-check'
  | 'shield-check-fill'
  | 'shield-error'
  | 'shield-error-fill'
  | 'shield-info'
  | 'shield-info-fill'
  | 'sidebar'
  | 'sidebar-fill'
  | 'soccerball'
  | 'soup'
  | 'speaker'
  | 'speaker-fill'
  | 'speaker-x'
  | 'speaker-x-fill'
  | 'speaker-bluetooth'
  | 'speaker-bluetooth-fill'
  | 'speaker-slash'
  | 'speaker-slash-fill'
  | 'square'
  | 'square-fill'
  | 'square-dashed'
  | 'square-on-square'
  | 'square-on-square-fill'
  | 'square-on-square-plus'
  | 'square-on-square-plus-fill'
  | 'star'
  | 'star-fill'
  | 'star-slash'
  | 'star-slash-fill'
  | 'sticker'
  | 'sticker-smiley'
  | 'sticker-slash'
  | 'stickerpack'
  | 'stickerpack-plus'
  | 'stop'
  | 'stop-fill'
  | 'stop-circle'
  | 'stop-circle-fill'
  | 'stop-square'
  | 'stop-square-fill'
  | 'stories'
  | 'stories-fill'
  | 'sun'
  | 'sun-fill'
  | 'sun-horizon'
  | 'sun-horizon-fill'
  | 'swap'
  | 'tada'
  | 'text-square'
  | 'text-square-fill'
  | 'text-outline'
  | 'textalign-[start]'
  | 'textalign-center'
  | 'textalign-[end]'
  | 'textalign-justifed'
  | 'texteffects'
  | 'texteffects-fill'
  | 'textformat-bold'
  | 'textformat-italic'
  | 'textformat-strikethrough'
  | 'textformat-monospace'
  | 'textformat-spoiler'
  | 'thumbsdown'
  | 'thumbsdown-fill'
  | 'thumbsup'
  | 'thumbsup-fill'
  | 'ticks'
  | 'timer'
  | 'timer-fill'
  | 'timer-slash'
  | 'timer-slash-fill'
  | 'timer-countdown-0'
  | 'timer-countdown-1'
  | 'timer-countdown-2'
  | 'timer-countdown-3'
  | 'timer-countdown-4'
  | 'timer-countdown-5'
  | 'timer-countdown-6'
  | 'timer-countdown-7'
  | 'timer-countdown-8'
  | 'timer-countdown-9'
  | 'timer-countdown-10'
  | 'timer-countdown-11'
  | 'timer-countdown-12'
  | 'trash'
  | 'trash-fill'
  | 'trending'
  | 'triangle'
  | 'triangle-fill'
  | 'tune'
  | 'typing'
  | 'typing-fill'
  | 'undo'
  | 'upload'
  | 'videocamera'
  | 'videocamera-fill'
  | 'videocamera-slash'
  | 'videocamera-slash-fill'
  | 'viewonce'
  | 'viewonce-dashed'
  | 'viewonce-slash'
  | 'visible'
  | 'visible-fill'
  | 'visible-slash'
  | 'visible-slash-fill'
  | 'wifi'
  | 'wifi-error'
  | 'x'
  | 'x-circle'
  | 'x-circle-fill'
  | 'x-circle-dashed'
  | 'x-square'
  | 'x-square-fill'
  | 'zoom-in'
  | 'zoom-out';


const BASE: Record<string, string> = {
  'album': '\u{E163}',
  'album-fill': '\u{E20D}',
  'album-plus': '\u{E294}',
  'album-plus-fill': '\u{E21F}',
  'appearance': '\u{E031}',
  'appearance-fill': '\u{E164}',
  'archive': '\u{E09B}',
  'archive-fill': '\u{E165}',
  'archive-down': '\u{E205}',
  'archive-down-fill': '\u{E206}',
  'archive-up': '\u{E09C}',
  'archive-up-fill': '\u{E166}',
  'archive-alt-down': '\u{E09D}',
  'archive-alt-down-fill': '\u{E167}',
  'archive-alt-up': '\u{E09E}',
  'archive-alt-up-fill': '\u{E168}',
  'arrow-[start]': '\u{E169}',
  'arrow-[end]': '\u{E16A}',
  'arrow-up': '\u{E16B}',
  'arrow-down': '\u{E16C}',
  'arrow-up[start]': '\u{E16D}',
  'arrow-up[end]': '\u{E16E}',
  'arrow-down[start]': '\u{E16F}',
  'arrow-down[end]': '\u{E170}',
  'arrow-circle-[start]': '\u{E00B}',
  'arrow-circle-[start]-fill': '\u{E003}',
  'arrow-circle-[end]': '\u{E00C}',
  'arrow-circle-[end]-fill': '\u{E004}',
  'arrow-circle-up': '\u{E00D}',
  'arrow-circle-up-fill': '\u{E005}',
  'arrow-circle-down': '\u{E00E}',
  'arrow-circle-down-fill': '\u{E006}',
  'arrow-circle-up[start]': '\u{E00F}',
  'arrow-circle-up[start]-fill': '\u{E007}',
  'arrow-circle-up[end]': '\u{E010}',
  'arrow-circle-up[end]-fill': '\u{E008}',
  'arrow-circle-down[start]': '\u{E011}',
  'arrow-circle-down[start]-fill': '\u{E009}',
  'arrow-circle-down[end]': '\u{E012}',
  'arrow-circle-down[end]-fill': '\u{E00A}',
  'arrow-square-[start]': '\u{E013}',
  'arrow-square-[start]-fill': '\u{E08A}',
  'arrow-square-[end]': '\u{E014}',
  'arrow-square-[end]-fill': '\u{E08B}',
  'arrow-square-up': '\u{E015}',
  'arrow-square-up-fill': '\u{E08C}',
  'arrow-square-down': '\u{E016}',
  'arrow-square-down-fill': '\u{E08D}',
  'arrow-square-up[start]': '\u{E017}',
  'arrow-square-up[start]-fill': '\u{E08E}',
  'arrow-square-up[end]': '\u{E018}',
  'arrow-square-up[end]-fill': '\u{E08F}',
  'arrow-square-down[start]': '\u{E019}',
  'arrow-square-down[start]-fill': '\u{E090}',
  'arrow-square-down[end]': '\u{E01A}',
  'arrow-square-down[end]-fill': '\u{E091}',
  'arrow-rectangle-[start]': '\u{E227}',
  'arrow-rectangle-[start]-fill': '\u{E231}',
  'arrow-rectangle-[end]': '\u{E228}',
  'arrow-rectangle-[end]-fill': '\u{E232}',
  'arrow-rectangle-up': '\u{E0CD}',
  'arrow-rectangle-up-fill': '\u{E173}',
  'arrow-rectangle-down': '\u{E229}',
  'arrow-rectangle-down-fill': '\u{E233}',
  'arrow-circle-dashed-[start]': '\u{E237}',
  'arrow-circle-dashed-[end]': '\u{E238}',
  'arrow-circle-dashed-up': '\u{E239}',
  'arrow-circle-dashed-down': '\u{E172}',
  'arrow-circle-dashed-up[start]': '\u{E29B}',
  'arrow-circle-dashed-up[end]': '\u{E29C}',
  'arrow-circle-dashed-down[start]': '\u{E29D}',
  'arrow-circle-dashed-down[end]': '\u{E29E}',
  'arrow-left-right': '\u{E0CF}',
  'arrow-up-down': '\u{E0CE}',
  'arrow-square-left-right': '\u{E297}',
  'arrow-square-left-right-fill': '\u{E299}',
  'arrow-square-up-down': '\u{E298}',
  'arrow-square-up-down-fill': '\u{E29A}',
  'arrow-outward-upleft-upright-downleft-downright': '\u{E117}',
  'arrow-outward-up[end]-down[start]': '\u{E118}',
  'arrow-outward-up[start]-down[end]': '\u{E119}',
  'arrow-inward-upleft-upright-downleft-downright': '\u{E11C}',
  'arrow-inward-up[end]-down[start]': '\u{E11D}',
  'arrow-inward-up[start]-down[end]': '\u{E11E}',
  'arrow-square-outward-up[end]-down[start]': '\u{E22C}',
  'arrow-square-outward-up[end]-down[start]-fill': '\u{E22D}',
  'arrow-square-outward-up[start]-down[end]': '\u{E22E}',
  'arrow-square-outward-up[start]-down[end]-fill': '\u{E22F}',
  'arrow-square-inward-up[end]-down[start]': '\u{E21B}',
  'arrow-square-inward-up[end]-down[start]-fill': '\u{E21C}',
  'arrow-square-inward-up[start]-down[end]': '\u{E21D}',
  'arrow-square-inward-up[start]-down[end]-fill': '\u{E21E}',
  'arrow-clockwise': '\u{E0C4}',
  'arrow-counterclockwise': '\u{E296}',
  'aspectratio': '\u{E134}',
  'aspectratio-fill': '\u{E176}',
  'at': '\u{E01B}',
  'attach': '\u{E058}',
  'audio': '\u{E01C}',
  'audio-rectangle': '\u{E178}',
  'audio-rectangle-fill': '\u{E179}',
  'audio-rectangle-slash': '\u{E2A3}',
  'audio-rectangle-slash-fill': '\u{E2A5}',
  'backspace': '\u{E203}',
  'backspace-fill': '\u{E20F}',
  'backup': '\u{E09F}',
  'backup-signal': '\u{E27E}',
  'backup-error': '\u{E0A0}',
  'badge': '\u{E099}',
  'badge-fill': '\u{E09A}',
  'badge-set': '\u{E0DA}',
  'badge-set-fill': '\u{E17D}',
  'bear': '\u{E0FE}',
  'bell': '\u{E01E}',
  'bell-fill': '\u{E248}',
  'bell-ring': '\u{E020}',
  'bell-ring-fill': '\u{E24A}',
  'bell-badge': '\u{E225}',
  'bell-badge-fill': '\u{E226}',
  'bell-slash': '\u{E01F}',
  'bell-slash-fill': '\u{E249}',
  'bell-sleep': '\u{E0A1}',
  'bell-sleep-fill': '\u{E24B}',
  'block': '\u{E002}',
  'blur': '\u{E0DB}',
  'blur-light': '\u{E211}',
  'blur-medium': '\u{E212}',
  'blur-heavy': '\u{E247}',
  'bolt': '\u{E0B8}',
  'bolt-fill': '\u{E218}',
  'boost': '\u{E0E2}',
  'boost-fill': '\u{E219}',
  'brushsize-thin': '\u{E0E1}',
  'brushsize-regular': '\u{E0E0}',
  'brushsize-medium': '\u{E0DF}',
  'brushsize-heavy': '\u{E0DE}',
  'building': '\u{E325}',
  'building-fill': '\u{E326}',
  'calendar': '\u{E0A2}',
  'calendar-fill': '\u{E2D4}',
  'calendar-week': '\u{E0A4}',
  'calendar-week-fill': '\u{E2D5}',
  'calendar-day': '\u{E0A5}',
  'calendar-day-fill': '\u{E2D7}',
  'calendar-blank': '\u{E0A3}',
  'calendar-blank-fill': '\u{E2D9}',
  'calendar-search': '\u{E0E3}',
  'camera': '\u{E0E4}',
  'camera-fill': '\u{E17E}',
  'camera-swap': '\u{E0E5}',
  'camera-swap-fill': '\u{E17F}',
  'car': '\u{E102}',
  'cellularbars': '\u{E339}',
  'check': '\u{E180}',
  'check-circle': '\u{E022}',
  'check-circle-fill': '\u{E182}',
  'check-square': '\u{E023}',
  'check-square-fill': '\u{E183}',
  'check-circle-on-check-circle': '\u{E181}',
  'check-circle-on-check-circle-fill': '\u{E1FC}',
  'chevron-[start]': '\u{E024}',
  'chevron-[end]': '\u{E025}',
  'chevron-up': '\u{E026}',
  'chevron-down': '\u{E027}',
  'chevron-circle-[start]': '\u{E028}',
  'chevron-circle-[start]-fill': '\u{E1F2}',
  'chevron-circle-[end]': '\u{E029}',
  'chevron-circle-[end]-fill': '\u{E1F3}',
  'chevron-circle-up': '\u{E02A}',
  'chevron-circle-up-fill': '\u{E1F4}',
  'chevron-circle-down': '\u{E02B}',
  'chevron-circle-down-fill': '\u{E1F5}',
  'chevron-square-[start]': '\u{E02C}',
  'chevron-square-[start]-fill': '\u{E1F6}',
  'chevron-square-[end]': '\u{E02D}',
  'chevron-square-[end]-fill': '\u{E1F7}',
  'chevron-square-up': '\u{E02E}',
  'chevron-square-up-fill': '\u{E1F8}',
  'chevron-square-down': '\u{E02F}',
  'chevron-square-down-fill': '\u{E1F9}',
  'chevron-shallow-[start]': '\u{E0E6}',
  'chevron-shallow-[end]': '\u{E0E7}',
  'chevron-shallow-up': '\u{E0E8}',
  'chevron-shallow-down': '\u{E0E9}',
  'chevron-outward-left-right': '\u{E207}',
  'chevron-outward-up-down': '\u{E081}',
  'chevron-rectangle-outward-upright-downleft': '\u{E2E8}',
  'chevron-rectangle-outward-up[end]-down[start]-fill': '\u{E2EE}',
  'circle': '\u{E160}',
  'circle-fill': '\u{E184}',
  'circle-dashed': '\u{E07A}',
  'clock': '\u{E265}',
  'clock-hour-1': '\u{E266}',
  'clock-hour-2': '\u{E267}',
  'clock-hour-3': '\u{E268}',
  'clock-hour-4': '\u{E269}',
  'clock-hour-5': '\u{E26A}',
  'clock-hour-6': '\u{E26B}',
  'clock-hour-7': '\u{E26C}',
  'clock-hour-8': '\u{E26D}',
  'clock-hour-9': '\u{E26E}',
  'clock-hour-10': '\u{E26F}',
  'clock-hour-11': '\u{E270}',
  'clock-hour-12': '\u{E271}',
  'compose': '\u{E0EA}',
  'connections': '\u{E0AD}',
  'connections-fill': '\u{E185}',
  'contrast': '\u{E281}',
  'copy': '\u{E0EB}',
  'copy-alt': '\u{E0EC}',
  'creditcard': '\u{E127}',
  'creditcard-fill': '\u{E187}',
  'crop': '\u{E0ED}',
  'crop-rotate': '\u{E0EE}',
  'crop-lock': '\u{E0EF}',
  'crop-unlock': '\u{E0F0}',
  'cube': '\u{E221}',
  'cube-fill': '\u{E222}',
  'cube-badge': '\u{E223}',
  'cube-badge-fill': '\u{E224}',
  'device-phone': '\u{E0F2}',
  'device-phone-fill': '\u{E18A}',
  'device-tablet': '\u{E0F3}',
  'device-tablet-fill': '\u{E18B}',
  'device-laptop': '\u{E0F4}',
  'device-laptop-fill': '\u{E18C}',
  'device-phone-laptop': '\u{E112}',
  'device-phone-laptop-fill': '\u{E252}',
  'download': '\u{E0C8}',
  'draghandle': '\u{E0F5}',
  'draghandle-alt': '\u{E0F6}',
  'drive': '\u{E288}',
  'drive-fill': '\u{E289}',
  'drive-down': '\u{E28A}',
  'drive-down-fill': '\u{E28B}',
  'dropper': '\u{E278}',
  'dropper-fill': '\u{E279}',
  'emoticon': '\u{E106}',
  'error': '\u{E11A}',
  'error-circle': '\u{E032}',
  'error-circle-fill': '\u{E093}',
  'error-triangle': '\u{E092}',
  'error-triangle-fill': '\u{E094}',
  'error-octagon': '\u{E033}',
  'error-octagon-fill': '\u{E18F}',
  'eyes': '\u{E0FD}',
  'face-smiling': '\u{E18D}',
  'face-smiling-fill': '\u{E18E}',
  'face-smiling-plus': '\u{E0F8}',
  'face-excited': '\u{E0F9}',
  'face-sad': '\u{E0FA}',
  'face-angry': '\u{E0FB}',
  'file': '\u{E034}',
  'file-fill': '\u{E190}',
  'file-slash': '\u{E0B1}',
  'file-slash-fill': '\u{E191}',
  'filter': '\u{E107}',
  'filter-circle': '\u{E108}',
  'filter-circle-fill': '\u{E1FA}',
  'flag': '\u{E105}',
  'flag-fill': '\u{E33D}',
  'flash': '\u{E109}',
  'flash-fill': '\u{E192}',
  'flash-slash': '\u{E10A}',
  'flash-slash-fill': '\u{E193}',
  'flash-auto': '\u{E10B}',
  'flash-auto-fill': '\u{E194}',
  'flip': '\u{E10C}',
  'folder': '\u{E0B2}',
  'folder-plus': '\u{E0B3}',
  'folder-minus': '\u{E274}',
  'folder-settings': '\u{E0B4}',
  'forward': '\u{E035}',
  'forward-fill': '\u{E036}',
  'fullscreen': '\u{E10D}',
  'gif': '\u{E037}',
  'gif-rectangle': '\u{E195}',
  'gif-rectangle-fill': '\u{E196}',
  'gift': '\u{E0B5}',
  'gift-fill': '\u{E253}',
  'globe': '\u{E0B6}',
  'globe-fill': '\u{E254}',
  'grid': '\u{E10E}',
  'grid-fill': '\u{E198}',
  'grid-rectangle': '\u{E10F}',
  'grid-rectangle-fill': '\u{E199}',
  'grid-sidebar': '\u{E13B}',
  'grid-sidebar-fill': '\u{E23C}',
  'group': '\u{E19B}',
  'group-fill': '\u{E19D}',
  'group-x': '\u{E19C}',
  'group-x-fill': '\u{E19F}',
  'group-question': '\u{E28C}',
  'group-question-fill': '\u{E28E}',
  'hd': '\u{E132}',
  'hd-fill': '\u{E27C}',
  'hd-slash': '\u{E133}',
  'hd-slash-fill': '\u{E27A}',
  'headphones': '\u{E110}',
  'headphones-fill': '\u{E1A3}',
  'heart': '\u{E039}',
  'heart-fill': '\u{E1A4}',
  'heart-plus': '\u{E0B7}',
  'heart-plus-fill': '\u{E1A5}',
  'hexagon': '\u{E2A7}',
  'hexagon-fill': '\u{E2A8}',
  'info': '\u{E21A}',
  'info-circle': '\u{E03B}',
  'info-circle-fill': '\u{E1A7}',
  'invite': '\u{E0B9}',
  'invite-fill': '\u{E2A9}',
  'key': '\u{E0BA}',
  'key-fill': '\u{E245}',
  'key-slash': '\u{E0BB}',
  'key-slash-fill': '\u{E246}',
  'key-horizontal': '\u{E327}',
  'key-horizontal-fill': '\u{E329}',
  'key-vertical': '\u{E32B}',
  'key-vertical-fill': '\u{E32C}',
  'keyboard': '\u{E111}',
  'keyboard-fill': '\u{E2AA}',
  'label': '\u{E27F}',
  'label-fill': '\u{E280}',
  'leave': '\u{E1AA}',
  'lightbulb': '\u{E103}',
  'link': '\u{E03E}',
  'link-alt': '\u{E03F}',
  'link-broken': '\u{E057}',
  'link-slash': '\u{E040}',
  'list-bullet': '\u{E113}',
  'list-circle': '\u{E114}',
  'location': '\u{E0BC}',
  'location-fill': '\u{E275}',
  'location-circle': '\u{E0BD}',
  'location-circle-fill': '\u{E1AC}',
  'lock': '\u{E041}',
  'lock-fill': '\u{E1AD}',
  'lock-open': '\u{E07D}',
  'lock-open-fill': '\u{E1AE}',
  'mathsymbols-square': '\u{E104}',
  'mathsymbols-square-fill': '\u{E33F}',
  'megaphone': '\u{E042}',
  'megaphone-fill': '\u{E2AE}',
  'menu': '\u{E11B}',
  'merge': '\u{E043}',
  'message': '\u{E0A6}',
  'message-fill': '\u{E1AF}',
  'message-badge': '\u{E0A7}',
  'message-badge-fill': '\u{E1B0}',
  'message-arrow-forward': '\u{E0A8}',
  'message-arrow-forward-fill': '\u{E1B1}',
  'message-check': '\u{E0A9}',
  'message-check-fill': '\u{E1B2}',
  'message-more': '\u{E0AA}',
  'message-more-fill': '\u{E1B3}',
  'message-x': '\u{E0AB}',
  'message-x-fill': '\u{E1B4}',
  'message-thread': '\u{E071}',
  'message-thread-fill': '\u{E072}',
  'mic': '\u{E055}',
  'mic-fill': '\u{E1B5}',
  'mic-slash': '\u{E056}',
  'mic-slash-fill': '\u{E1B6}',
  'minus': '\u{E1B7}',
  'minus-circle': '\u{E1B8}',
  'minus-circle-fill': '\u{E1B9}',
  'minus-square': '\u{E059}',
  'minus-square-fill': '\u{E1BA}',
  'missed-incoming': '\u{E05A}',
  'missed-outgoing': '\u{E05B}',
  'moon': '\u{E0BE}',
  'moon-fill': '\u{E0D9}',
  'moon-slash': '\u{E209}',
  'moon-slash-fill': '\u{E20A}',
  'more': '\u{E120}',
  'more-vertical': '\u{E2AF}',
  'more-circle': '\u{E121}',
  'more-circle-fill': '\u{E208}',
  'more-square': '\u{E2D0}',
  'more-square-fill': '\u{E2D1}',
  'note': '\u{E095}',
  'note-fill': '\u{E2D2}',
  'nothing': '\u{E189}',
  'number': '\u{E0BF}',
  'number-square': '\u{E0C0}',
  'number-square-fill': '\u{E1BC}',
  'numberpad': '\u{E123}',
  'octagon': '\u{E2B0}',
  'octagon-fill': '\u{E2B1}',
  'open': '\u{E0C1}',
  'palette': '\u{E0AC}',
  'palette-fill': '\u{E1BD}',
  'pause': '\u{E124}',
  'pause-fill': '\u{E1BE}',
  'pause-circle': '\u{E125}',
  'pause-circle-fill': '\u{E1BF}',
  'pause-square': '\u{E126}',
  'pause-square-fill': '\u{E1C0}',
  'pencil': '\u{E030}',
  'pencil-fill': '\u{E1C1}',
  'person': '\u{E05D}',
  'person-fill': '\u{E1C3}',
  'person-check': '\u{E1FE}',
  'person-check-fill': '\u{E255}',
  'person-key': '\u{E32D}',
  'person-key-fill': '\u{E32F}',
  'person-plus': '\u{E1FF}',
  'person-plus-fill': '\u{E257}',
  'person-minus': '\u{E200}',
  'person-minus-fill': '\u{E259}',
  'person-x': '\u{E201}',
  'person-x-fill': '\u{E25B}',
  'person-question': '\u{E202}',
  'person-question-fill': '\u{E25D}',
  'person-circle': '\u{E05E}',
  'person-circle-fill': '\u{E1C4}',
  'person-circle-plus': '\u{E128}',
  'person-square': '\u{E129}',
  'person-square-fill': '\u{E1C5}',
  'person-rectangle': '\u{E12A}',
  'person-rectangle-fill': '\u{E1C6}',
  'person-background': '\u{E2C5}',
  'person-background-fill': '\u{E2C6}',
  'phone': '\u{E063}',
  'phone-fill': '\u{E064}',
  'phone-horiztonal': '\u{E12B}',
  'phone-horiztonal-fill': '\u{E25F}',
  'phone-plus': '\u{E12C}',
  'phone-plus-fill': '\u{E260}',
  'phone-speaker': '\u{E12D}',
  'phone-speaker-fill': '\u{E261}',
  'phone-slash': '\u{E29F}',
  'phone-slash-fill': '\u{E2A0}',
  'photo': '\u{E1C8}',
  'photo-fill': '\u{E290}',
  'photo-slash': '\u{E1C9}',
  'photo-slash-fill': '\u{E292}',
  'piechart': '\u{E0F1}',
  'piechart-fill': '\u{E1CA}',
  'pin': '\u{E12E}',
  'pin-fill': '\u{E1CB}',
  'pin-slash': '\u{E12F}',
  'pin-slash-fill': '\u{E1CC}',
  'pip': '\u{E130}',
  'pip-fill': '\u{E23E}',
  'play': '\u{E067}',
  'play-fill': '\u{E1CD}',
  'play-slash': '\u{E131}',
  'play-slash-fill': '\u{E1D0}',
  'play-circle': '\u{E068}',
  'play-circle-fill': '\u{E1CE}',
  'play-square': '\u{E069}',
  'play-square-fill': '\u{E1CF}',
  'play-rectangle': '\u{E1E2}',
  'play-rectangle-fill': '\u{E1E4}',
  'play-rectangle-slash': '\u{E1E3}',
  'play-rectangle-slash-fill': '\u{E1E6}',
  'plus': '\u{E1D1}',
  'plus-circle': '\u{E1D2}',
  'plus-circle-fill': '\u{E1D3}',
  'plus-square': '\u{E06C}',
  'plus-square-fill': '\u{E1D4}',
  'poll': '\u{E082}',
  'poll-fill': '\u{E083}',
  'press': '\u{E14A}',
  'press-fill': '\u{E14B}',
  'qrcode': '\u{E0C2}',
  'question': '\u{E11F}',
  'question-circle': '\u{E0D8}',
  'question-circle-fill': '\u{E1A6}',
  'raisehand': '\u{E07E}',
  'raisehand-fill': '\u{E084}',
  'receipt': '\u{E135}',
  'receipt-fill': '\u{E2B2}',
  'recent': '\u{E0C3}',
  'recent-fill': '\u{E2B4}',
  'rectangle': '\u{E162}',
  'rectangle-fill': '\u{E1D6}',
  'rectangle-dashed': '\u{E214}',
  'rectangle-portrait': '\u{E2B5}',
  'rectangle-portrait-fill': '\u{E2B6}',
  'rectangle-portrait-dashed': '\u{E2B7}',
  'redo': '\u{E0C6}',
  'reply': '\u{E06D}',
  'reply-fill': '\u{E06E}',
  'rotate': '\u{E137}',
  'rotate-fill': '\u{E2B8}',
  'scan': '\u{E138}',
  'scan-qrcode': '\u{E216}',
  'scribble': '\u{E0F7}',
  'seal-fill': '\u{E2BA}',
  'seal': '\u{E2B9}',
  'seal-check': '\u{E086}',
  'seal-check-fill': '\u{E087}',
  'search': '\u{E0C7}',
  'securitykey': '\u{E2DF}',
  'securitykey-fill': '\u{E2E0}',
  'send': '\u{E20B}',
  'send-fill': '\u{E0C9}',
  'settings': '\u{E0CA}',
  'settings-fill': '\u{E0CB}',
  'settings-alt': '\u{E0CC}',
  'share': '\u{E139}',
  'share-alt': '\u{E13A}',
  'shield': '\u{E2BB}',
  'shield-fill': '\u{E2BC}',
  'shield-check': '\u{E06F}',
  'shield-check-fill': '\u{E1D8}',
  'shield-error': '\u{E2BD}',
  'shield-error-fill': '\u{E2BE}',
  'shield-info': '\u{E2BF}',
  'shield-info-fill': '\u{E2C0}',
  'sidebar': '\u{E13C}',
  'sidebar-fill': '\u{E243}',
  'soccerball': '\u{E101}',
  'soup': '\u{E100}',
  'speaker': '\u{E13F}',
  'speaker-fill': '\u{E23F}',
  'speaker-x': '\u{E140}',
  'speaker-x-fill': '\u{E240}',
  'speaker-bluetooth': '\u{E141}',
  'speaker-bluetooth-fill': '\u{E241}',
  'speaker-slash': '\u{E142}',
  'speaker-slash-fill': '\u{E242}',
  'square': '\u{E161}',
  'square-fill': '\u{E1FB}',
  'square-dashed': '\u{E17C}',
  'square-on-square': '\u{E286}',
  'square-on-square-fill': '\u{E287}',
  'square-on-square-plus': '\u{E122}',
  'square-on-square-plus-fill': '\u{E1BB}',
  'star': '\u{E0AF}',
  'star-fill': '\u{E0B0}',
  'star-slash': '\u{E276}',
  'star-slash-fill': '\u{E277}',
  'sticker': '\u{E070}',
  'sticker-smiley': '\u{E143}',
  'sticker-slash': '\u{E144}',
  'stickerpack': '\u{E145}',
  'stickerpack-plus': '\u{E146}',
  'stop': '\u{E147}',
  'stop-fill': '\u{E1D9}',
  'stop-circle': '\u{E148}',
  'stop-circle-fill': '\u{E1DA}',
  'stop-square': '\u{E149}',
  'stop-square-fill': '\u{E1DB}',
  'stories': '\u{E0D0}',
  'stories-fill': '\u{E0D1}',
  'sun': '\u{E0D2}',
  'sun-fill': '\u{E1DC}',
  'sun-horizon': '\u{E0D3}',
  'sun-horizon-fill': '\u{E1DD}',
  'swap': '\u{E0D4}',
  'tada': '\u{E0FF}',
  'text-square': '\u{E14D}',
  'text-square-fill': '\u{E1DE}',
  'text-outline': '\u{E14E}',
  'textalign-[start]': '\u{E14F}',
  'textalign-center': '\u{E150}',
  'textalign-[end]': '\u{E151}',
  'textalign-justifed': '\u{E152}',
  'texteffects': '\u{E153}',
  'texteffects-fill': '\u{E1DF}',
  'textformat-bold': '\u{E154}',
  'textformat-italic': '\u{E155}',
  'textformat-strikethrough': '\u{E156}',
  'textformat-monospace': '\u{E157}',
  'textformat-spoiler': '\u{E158}',
  'thumbsdown': '\u{E262}',
  'thumbsdown-fill': '\u{E263}',
  'thumbsup': '\u{E0FC}',
  'thumbsup-fill': '\u{E264}',
  'ticks': '\u{E044}',
  'timer': '\u{E073}',
  'timer-fill': '\u{E1E0}',
  'timer-slash': '\u{E074}',
  'timer-slash-fill': '\u{E1E1}',
  'timer-countdown-0': '\u{E048}',
  'timer-countdown-1': '\u{E049}',
  'timer-countdown-2': '\u{E04A}',
  'timer-countdown-3': '\u{E04B}',
  'timer-countdown-4': '\u{E04C}',
  'timer-countdown-5': '\u{E04D}',
  'timer-countdown-6': '\u{E04E}',
  'timer-countdown-7': '\u{E04F}',
  'timer-countdown-8': '\u{E050}',
  'timer-countdown-9': '\u{E051}',
  'timer-countdown-10': '\u{E052}',
  'timer-countdown-11': '\u{E053}',
  'timer-countdown-12': '\u{E054}',
  'trash': '\u{E0D5}',
  'trash-fill': '\u{E0D6}',
  'trending': '\u{E159}',
  'triangle': '\u{E2A1}',
  'triangle-fill': '\u{E2A2}',
  'tune': '\u{E15A}',
  'typing': '\u{E284}',
  'typing-fill': '\u{E285}',
  'undo': '\u{E0C5}',
  'upload': '\u{E0D7}',
  'videocamera': '\u{E1E8}',
  'videocamera-fill': '\u{E1EA}',
  'videocamera-slash': '\u{E1E9}',
  'videocamera-slash-fill': '\u{E1EB}',
  'viewonce': '\u{E078}',
  'viewonce-dashed': '\u{E079}',
  'viewonce-slash': '\u{E204}',
  'visible': '\u{E15B}',
  'visible-fill': '\u{E2CE}',
  'visible-slash': '\u{E15C}',
  'visible-slash-fill': '\u{E2CF}',
  'wifi': '\u{E15D}',
  'wifi-error': '\u{E15E}',
  'x': '\u{E1ED}',
  'x-circle': '\u{E1EE}',
  'x-circle-fill': '\u{E1F0}',
  'x-circle-dashed': '\u{E15F}',
  'x-square': '\u{E1EF}',
  'x-square-fill': '\u{E1F1}',
  'zoom-in': '\u{E282}',
  'zoom-out': '\u{E283}',
};

const RTL: Record<string, string> = {
  'arrow-[end]': '\u{E169}',
  'arrow-[start]': '\u{E16A}',
  'arrow-up[end]': '\u{E16D}',
  'arrow-up[start]': '\u{E16E}',
  'arrow-down[end]': '\u{E16F}',
  'arrow-down[start]': '\u{E170}',
  'arrow-circle-[end]': '\u{E00B}',
  'arrow-circle-[end]-fill': '\u{E003}',
  'arrow-circle-[start]': '\u{E00C}',
  'arrow-circle-[start]-fill': '\u{E004}',
  'arrow-circle-up[end]': '\u{E00F}',
  'arrow-circle-up[end]-fill': '\u{E007}',
  'arrow-circle-up[start]': '\u{E010}',
  'arrow-circle-up[start]-fill': '\u{E008}',
  'arrow-circle-down[end]': '\u{E011}',
  'arrow-circle-down[end]-fill': '\u{E009}',
  'arrow-circle-down[start]': '\u{E012}',
  'arrow-circle-down[start]-fill': '\u{E00A}',
  'arrow-square-[end]': '\u{E013}',
  'arrow-square-[end]-fill': '\u{E08A}',
  'arrow-square-[start]': '\u{E014}',
  'arrow-square-[start]-fill': '\u{E08B}',
  'arrow-square-up[end]': '\u{E017}',
  'arrow-square-up[end]-fill': '\u{E08E}',
  'arrow-square-up[start]': '\u{E018}',
  'arrow-square-up[start]-fill': '\u{E08F}',
  'arrow-square-down[end]': '\u{E019}',
  'arrow-square-down[end]-fill': '\u{E090}',
  'arrow-square-down[start]': '\u{E01A}',
  'arrow-square-down[start]-fill': '\u{E091}',
  'arrow-rectangle-[end]': '\u{E227}',
  'arrow-rectangle-[end]-fill': '\u{E231}',
  'arrow-rectangle-[start]': '\u{E228}',
  'arrow-rectangle-[start]-fill': '\u{E232}',
  'arrow-circle-dashed-[end]': '\u{E237}',
  'arrow-circle-dashed-[start]': '\u{E238}',
  'arrow-circle-dashed-up[end]': '\u{E29B}',
  'arrow-circle-dashed-up[start]': '\u{E29C}',
  'arrow-circle-dashed-down[end]': '\u{E29D}',
  'arrow-circle-dashed-down[start]': '\u{E29E}',
  'arrow-outward-up[start]-down[end]': '\u{E118}',
  'arrow-outward-up[end]-down[start]': '\u{E119}',
  'arrow-inward-up[start]-down[end]': '\u{E11D}',
  'arrow-inward-up[end]-down[start]': '\u{E11E}',
  'arrow-square-outward-up[start]-down[end]': '\u{E22C}',
  'arrow-square-outward-up[start]-down[end]-fill': '\u{E22D}',
  'arrow-square-outward-up[end]-down[start]': '\u{E22E}',
  'arrow-square-outward-up[end]-down[start]-fill': '\u{E22F}',
  'arrow-square-inward-up[start]-down[end]': '\u{E21B}',
  'arrow-square-inward-up[start]-down[end]-fill': '\u{E21C}',
  'arrow-square-inward-up[end]-down[start]': '\u{E21D}',
  'arrow-square-inward-up[end]-down[start]-fill': '\u{E21E}',
  'backspace': '\u{E17B}',
  'backspace-fill': '\u{E210}',
  'bell-badge': '\u{E303}',
  'bell-badge-fill': '\u{E304}',
  'calendar-day': '\u{E2D6}',
  'calendar-day-fill': '\u{E2D8}',
  'chevron-[end]': '\u{E024}',
  'chevron-[start]': '\u{E025}',
  'chevron-circle-[end]': '\u{E028}',
  'chevron-circle-[end]-fill': '\u{E1F2}',
  'chevron-circle-[start]': '\u{E029}',
  'chevron-circle-[start]-fill': '\u{E1F3}',
  'chevron-square-[end]': '\u{E02C}',
  'chevron-square-[end]-fill': '\u{E1F6}',
  'chevron-square-[start]': '\u{E02D}',
  'chevron-square-[start]-fill': '\u{E1F7}',
  'chevron-shallow-[end]': '\u{E0E6}',
  'chevron-shallow-[start]': '\u{E0E7}',
  'chevron-rectangle-outward-up[start]-down[end]-fill': '\u{E2EE}',
  'cube-badge': '\u{E323}',
  'cube-badge-fill': '\u{E324}',
  'forward': '\u{E2E1}',
  'forward-fill': '\u{E2E2}',
  'leave': '\u{E1AB}',
  'list-bullet': '\u{E115}',
  'list-circle': '\u{E116}',
  'megaphone': '\u{E2E6}',
  'megaphone-fill': '\u{E2E7}',
  'message-badge': '\u{E2EA}',
  'message-badge-fill': '\u{E2EB}',
  'message-arrow-forward': '\u{E2EC}',
  'message-arrow-forward-fill': '\u{E2ED}',
  'note': '\u{E096}',
  'note-fill': '\u{E2D3}',
  'open': '\u{E23B}',
  'person-circle-plus': '\u{E321}',
  'poll': '\u{E272}',
  'poll-fill': '\u{E273}',
  'receipt': '\u{E136}',
  'receipt-fill': '\u{E2B3}',
  'redo': '\u{E2F6}',
  'reply': '\u{E2F7}',
  'reply-fill': '\u{E2F8}',
  'speaker': '\u{E2F9}',
  'speaker-fill': '\u{E2FA}',
  'speaker-x': '\u{E2FB}',
  'speaker-x-fill': '\u{E2FC}',
  'speaker-bluetooth': '\u{E2FD}',
  'speaker-bluetooth-fill': '\u{E2FE}',
  'speaker-slash': '\u{E2FF}',
  'speaker-slash-fill': '\u{E300}',
  'textalign-[end]': '\u{E14F}',
  'textalign-[start]': '\u{E151}',
  'trending': '\u{E301}',
  'undo': '\u{E302}',
};

const WIDE: Record<string, string> = {
  'album': '\u{E001}',
  'album-fill': '\u{E20E}',
  'album-plus': '\u{E295}',
  'album-plus-fill': '\u{E220}',
  'arrow-rectangle-[start]': '\u{E22A}',
  'arrow-rectangle-[start]-fill': '\u{E234}',
  'arrow-rectangle-[end]': '\u{E22B}',
  'arrow-rectangle-[end]-fill': '\u{E235}',
  'arrow-rectangle-up': '\u{E171}',
  'arrow-rectangle-up-fill': '\u{E174}',
  'arrow-rectangle-down': '\u{E230}',
  'arrow-rectangle-down-fill': '\u{E236}',
  'aspectratio': '\u{E175}',
  'aspectratio-fill': '\u{E177}',
  'audio-rectangle': '\u{E01D}',
  'audio-rectangle-fill': '\u{E17A}',
  'audio-rectangle-slash': '\u{E2A4}',
  'audio-rectangle-slash-fill': '\u{E2A6}',
  'check-circle-on-check-circle': '\u{E046}',
  'check-circle-on-check-circle-fill': '\u{E047}',
  'chevron-rectangle-outward-up[end]-down[start]': '\u{E2E9}',
  'chevron-rectangle-outward-up[end]-down[start]-fill': '\u{E2EF}',
  'creditcard': '\u{E186}',
  'creditcard-fill': '\u{E188}',
  'face-smiling-plus': '\u{E20C}',
  'gif-rectangle': '\u{E097}',
  'gif-rectangle-fill': '\u{E098}',
  'grid-rectangle': '\u{E197}',
  'grid-rectangle-fill': '\u{E19A}',
  'grid-sidebar': '\u{E213}',
  'grid-sidebar-fill': '\u{E23D}',
  'group': '\u{E038}',
  'group-fill': '\u{E19E}',
  'group-x': '\u{E0AE}',
  'group-x-fill': '\u{E1A0}',
  'group-question': '\u{E28D}',
  'group-question-fill': '\u{E28F}',
  'hd': '\u{E1A1}',
  'hd-fill': '\u{E27D}',
  'hd-slash': '\u{E1A2}',
  'hd-slash-fill': '\u{E27B}',
  'invite': '\u{E1A8}',
  'invite-fill': '\u{E2DE}',
  'key-horizontal': '\u{E328}',
  'key-horizontal-fill': '\u{E32A}',
  'keyboard': '\u{E1A9}',
  'keyboard-fill': '\u{E2AB}',
  'person-check': '\u{E05F}',
  'person-check-fill': '\u{E256}',
  'person-plus': '\u{E061}',
  'person-plus-fill': '\u{E258}',
  'person-minus': '\u{E062}',
  'person-minus-fill': '\u{E25A}',
  'person-x': '\u{E060}',
  'person-x-fill': '\u{E25C}',
  'person-question': '\u{E06A}',
  'person-question-fill': '\u{E25E}',
  'person-circle-plus': '\u{E2DD}',
  'person-rectangle': '\u{E1C2}',
  'person-rectangle-fill': '\u{E1C7}',
  'photo': '\u{E065}',
  'photo-fill': '\u{E291}',
  'photo-slash': '\u{E066}',
  'photo-slash-fill': '\u{E293}',
  'play-rectangle': '\u{E088}',
  'play-rectangle-fill': '\u{E1E5}',
  'play-rectangle-slash': '\u{E089}',
  'play-rectangle-slash-fill': '\u{E1E7}',
  'rectangle': '\u{E1D5}',
  'rectangle-fill': '\u{E1D7}',
  'rectangle-dashed': '\u{E215}',
  'sidebar': '\u{E217}',
  'sidebar-fill': '\u{E244}',
  'videocamera': '\u{E075}',
  'videocamera-fill': '\u{E077}',
  'videocamera-slash': '\u{E076}',
  'videocamera-slash-fill': '\u{E1EC}',
};

const WIDE_RTL: Record<string, string> = {
  'arrow-rectangle-[end]': '\u{E22A}',
  'arrow-rectangle-[end]-fill': '\u{E234}',
  'arrow-rectangle-[start]': '\u{E22B}',
  'arrow-rectangle-[start]-fill': '\u{E235}',
  'chevron-rectangle-outward-up[start]-down[end]': '\u{E2E9}',
  'chevron-rectangle-outward-up[start]-down[end]-fill': '\u{E2EF}',
  'person-circle-plus': '\u{E322}',
};

/** @testexport */
export function _getAllAxoSymbolNames(): ReadonlyArray<_AxoSymbolName> {
  return Object.keys(BASE) as Array<_AxoSymbolName>;
}

export function _getAxoSymbolIcon(
  name: _AxoSymbolName,
  dir: 'ltr' | 'rtl'
): string {
  const value = dir === 'rtl'
    ? (WIDE_RTL[name] ?? RTL[name] ?? WIDE[name] ?? BASE[name])
    : (WIDE[name] ?? BASE[name]);
  if (value == null) {
    throw new TypeError(`Invalid symbol name for icon: ${name}`);
  }
  return value;
}

export function _getAxoSymbolInlineGlyph(
  name: _AxoSymbolName,
  dir: 'ltr' | 'rtl'
): string {
  const value = dir === 'rtl'
    ? (RTL[name] ?? BASE[name])
    : BASE[name];
  if (value == null) {
    throw new TypeError(`Invalid symbol name for inline glyph: ${name}`);
  }
  return value;
}
