// Copyright 2021 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

import type { actions as accounts } from './ducks/accounts.js';
import type { actions as app } from './ducks/app.js';
import type { actions as audioPlayer } from './ducks/audioPlayer.js';
import type { actions as audioRecorder } from './ducks/audioRecorder.js';
import type { actions as badges } from './ducks/badges.js';
import type { actions as callHistory } from './ducks/callHistory.js';
import type { actions as calling } from './ducks/calling.js';
import type { actions as chatFolders } from './ducks/chatFolders.js';
import type { actions as composer } from './ducks/composer.js';
import type { actions as conversations } from './ducks/conversations.js';
import type { actions as crashReports } from './ducks/crashReports.js';
import type { actions as donations } from './ducks/donations.js';
import type { actions as emojis } from './ducks/emojis.js';
import type { actions as expiration } from './ducks/expiration.js';
import type { actions as gifs } from './ducks/gifs.js';
import type { actions as globalModals } from './ducks/globalModals.js';
import type { actions as inbox } from './ducks/inbox.js';
import type { actions as installer } from './ducks/installer.js';
import type { actions as items } from './ducks/items.js';
import type { actions as lightbox } from './ducks/lightbox.js';
import type { actions as linkPreviews } from './ducks/linkPreviews.js';
import type { actions as mediaGallery } from './ducks/mediaGallery.js';
import type { actions as nav } from './ducks/nav.js';
import type { actions as network } from './ducks/network.js';
import type { actions as notificationProfiles } from './ducks/notificationProfiles.js';
import type { actions as safetyNumber } from './ducks/safetyNumber.js';
import type { actions as search } from './ducks/search.js';
import type { actions as stickers } from './ducks/stickers.js';
import type { actions as stories } from './ducks/stories.js';
import type { actions as storyDistributionLists } from './ducks/storyDistributionLists.js';
import type { actions as toast } from './ducks/toast.js';
import type { actions as updates } from './ducks/updates.js';
import type { actions as user } from './ducks/user.js';
import type { actions as username } from './ducks/username.js';

export type ReduxActions = {
  accounts: typeof accounts;
  app: typeof app;
  audioPlayer: typeof audioPlayer;
  audioRecorder: typeof audioRecorder;
  badges: typeof badges;
  callHistory: typeof callHistory;
  calling: typeof calling;
  chatFolders: typeof chatFolders;
  composer: typeof composer;
  conversations: typeof conversations;
  crashReports: typeof crashReports;
  donations: typeof donations;
  emojis: typeof emojis;
  expiration: typeof expiration;
  gifs: typeof gifs;
  globalModals: typeof globalModals;
  inbox: typeof inbox;
  installer: typeof installer;
  items: typeof items;
  lightbox: typeof lightbox;
  linkPreviews: typeof linkPreviews;
  mediaGallery: typeof mediaGallery;
  nav: typeof nav;
  network: typeof network;
  notificationProfiles: typeof notificationProfiles;
  safetyNumber: typeof safetyNumber;
  search: typeof search;
  stickers: typeof stickers;
  stories: typeof stories;
  storyDistributionLists: typeof storyDistributionLists;
  toast: typeof toast;
  updates: typeof updates;
  user: typeof user;
  username: typeof username;
};
