# Copyright 2026 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name: Publish Packages
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: ${{ github.repository == 'signalapp/Signal-Desktop-Private' }}
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 45

    permissions:
      id-token: write # Required for OIDC
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - name: Setup node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
          package-manager-cache: false

      - name: Install node_modules
        run: pnpm install --frozen-lockfile

      - name: Publish
        id: changesets
        uses: changesets/action@c47fa68bd43bb8ae0bae7e558622593deebf5955
        with:
          commit-message: Publish Packages
          pr-title: Publish Packages
          version-script: pnpm changeset:version
          publish-script: pnpm changeset:publish
          create-github-releases: false
          push-git-tags: true
          commit-mode: github-api
          github-token: ${{ secrets.AUTOMATED_GITHUB_PAT }}
